function Offspring = mutation(Population,N,type,Parameter)
%GA - Genetic operators for real, binary, and permutation based encodings.
%
%   Off = GA(P) returns the offsprings generated by genetic operators,
%   where P1 is a set of parents. If P is an array of INDIVIDUAL objects,
%   then Off is also an array of INDIVIDUAL objects; while if P is a matrix
%   of decision variables, then Off is also a matrix of decision variables,
%   i.e., the offsprings will not be evaluated. P is split into two subsets
%   P1 and P2 with the same size, and each object/row of P1 and P2 is used
%   to generate TWO offsprings. Different operators are used for real,
%   binary, and permutation based encodings, respectively.
%
%   Off = GA(P,{proC,disC,proM,disM}) specifies the parameters of
%   operators, where proC is the probabilities of doing crossover, disC is
%   the distribution index of simulated binary crossover, proM is the
%   expectation of number of bits doing mutation, and disM is the
%   distribution index of polynomial mutation.

    %% Parameter setting
    if nargin > 3
        [proM,disM] = deal(Parameter{:});
    else
        [proM,disM] = deal(1,20);
    end
    if isa(Population,'INDIVIDUAL')
        calObj = true;
        switch type
            case 'upper'
                Population = Population.upper_decs;
            case 'lower'
                Population = Population.lower_decs;
        end
    else
        calObj = false;
    end
    
    Offspring = repmat(Population,N,1);
    
    [N,D] = size(Offspring);
    
    % Polynomial mutation
    Global=GLOBAL.GetObj();
    switch type
        case 'upper'
            Lower = repmat(Global.upper_domain(1,:),N,1);
            Upper = repmat(Global.upper_domain(2,:),N,1);
        case 'lower'
            if ~iscell(Global.lower_domain)
                Lower = repmat(Global.lower_domain(1,:),N,1);
                Upper = repmat(Global.lower_domain(2,:),N,1);
            else
                Lower = repmat(Global.lower_domain{1},1,1);
                Upper = repmat(Global.lower_domain{2},1,1);
            end
    end
    Site  = rand(N,D) < proM;
    mu    = rand(N,D);
    temp  = Site & mu<=0.5;
    Offspring       = min(max(Offspring,Lower),Upper);
    Offspring(temp) = Offspring(temp)+(Upper(temp)-Lower(temp)).*((2.*mu(temp)+(1-2.*mu(temp)).*...
        (1-(Offspring(temp)-Lower(temp))./(Upper(temp)-Lower(temp))).^(disM+1)).^(1/(disM+1))-1);
    temp = Site & mu>0.5;
    Offspring(temp) = Offspring(temp)+(Upper(temp)-Lower(temp)).*(1-(2.*(1-mu(temp))+2.*(mu(temp)-0.5).*...
        (1-(Upper(temp)-Offspring(temp))./(Upper(temp)-Lower(temp))).^(disM+1)).^(1/(disM+1)));

    if calObj
        Offspring = INDIVIDUAL(Offspring,type);
    end
end